# Generated by Django 3.2.7 on 2021-10-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
