# Generated by Django 3.2.7 on 2021-10-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_alter_producer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={},
        ),
    ]
