# Generated by Django 3.2.7 on 2021-09-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('picture', models.FileField(upload_to='pictures/')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producers.producer')),
            ],
        ),
    ]
